### ISSUE TITLE
Trace all classes and methods of an Android application ordered by their calling priority

### ISSUE THREAD

**Issue by iceparadise13** [dpnishant/appmon#51]
I would like to trace all methods priority without set class name. How can I do this?

**Comment by dpnishant** [comment]
@iceparadise13 You have to hook every method in every class. And it will make the app tremendously slow. Still you can look at this snippet here: https://github.com/dpnishant/appmon/blob/2b30d68b4a45a7927a1a5deb9e9a76b89bdf4963/tracer/android_tracer.py#L115-L123

Since your question is generic and not necessarily related to AppMon. I would appreciate if you ask such questions in other channels e.g. twitter, email etc. and not create issues in this project.
